### ISSUE TITLE
Adding OperandBindInfo 

### ISSUE THREAD

**Issue by gyliu513** [IBM/operand-deployment-lifecycle-manager#114]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

The Operand BindInfo CR identifies a secret and/or configmap information from a deployed operand that should be shared with those creating OperandRequests CRs for the operand. This information is used to interact with the deployed operand.

An example of the Operand BindInfo CR is below:

```yaml
apiVersion: odlm.ibm.com/v1alpha1
kind: OperandBindInfo
metadata:
  name: publiciambinding
spec:
  operand: iam
  registry: comon-services
  description: "Binding information that should be accessible to IAM adopters"
  bindings:
  - scope: public
    secret: iambindsecret
    configmap: iamconfigmap
```

The parameters are described below:

- operand: specifies the name of the operand from the OperandRegistry in the same namespace as the
- bindings: specify the names of public and private secrets and configmaps that contain information that should be shared with requestor who want to interact with the operand. An OperandBindInfo CR can have at MOST one public scoped binding and one private scope binding. Private binding information is only shared between operands in the same namespace.
- secret: specifies that name of a secret that contains information that should be shared with a requestor.
- configmap: specifies that name of a configmap contains information that should be shared with requestors.
