### ISSUE TITLE
OperanRequest status phase display incorrect

### ISSUE THREAD

**Issue by DanielXLee** [IBM/operand-deployment-lifecycle-manager#218]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Cluster phase is `Running` when operator `ibm-mongodb-operator` operandPhase is `Ready for Deployment`
```yaml
  members:
    - name: ibm-mongodb-operator
      phase:
        operandPhase: Ready for Deployment
        operatorPhase: Succeeded
    - name: ibm-monitoring-exporters-operator
      phase:
        operandPhase: Running
        operatorPhase: Succeeded
    - name: ibm-monitoring-prometheusext-operator
      phase:
        operandPhase: Running
        operatorPhase: Succeeded
    - name: ibm-healthcheck-operator
      phase:
        operandPhase: Running
        operatorPhase: Succeeded
  phase: Running
```

**What did you expect to happen:**
Cluster phase should be `Creating` when operator `ibm-mongodb-operator` operandPhase is `Ready for Deployment`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ODLM version:
- Minikube/KIND/OCP version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
