### ISSUE TITLE
Errors when watching multi-crds within one controller 

### ISSUE THREAD

**Issue by horis233** [IBM/operand-deployment-lifecycle-manager#317]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

refer #314  

Although we watch three CRDs in the OperandRequest controller
```
	// Watch for changes to primary resource OperandRequest
	err = c.Watch(&source.Kind{Type: &operatorv1alpha1.OperandRequest{}}, &handler.EnqueueRequestForObject{})
	if err != nil {
		return err
	}

	// Watch for changes to primary resource OperandRegistry
	err = c.Watch(&source.Kind{Type: &operatorv1alpha1.OperandRegistry{}}, &handler.EnqueueRequestForObject{})
	if err != nil {
		return err
	}

	// Watch for changes to primary resource OperandConfig
	err = c.Watch(&source.Kind{Type: &operatorv1alpha1.OperandConfig{}}, &handler.EnqueueRequestForObject{})
	if err != nil {
		return err
	}
```
The controller will only reconcile if the CR is `OperandRequest`.
```
func (r *ReconcileOperandRequest) Reconcile(request reconcile.Request) (reconcile.Result, error) {

	// Fetch the OperandRequest instance
	requestInstance := &operatorv1alpha1.OperandRequest{}
	if err := r.client.Get(context.TODO(), request.NamespacedName, requestInstance); err != nil {
		// Error reading the object - requeue the request.
		return reconcile.Result{}, client.IgnoreNotFound(err)
	}
```

This defect is hidden because in 1Q we deploy `OperandRequest`, `OperandRegistry` and `OperandConfig` in the same namespace with the same name.

Moreover, the `OperandBindInfo` controller can't watch the update of `OperandRegistry` status is because of the same reason.

@DanielXLee 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ODLM version:
- Minikube/KIND/OCP version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by horis233** [comment]
@chenzhiwei @DanielXLee 

I think we may add a `requestList` field in the `OperandConfig` and `OperandRegistry`, which include all the `OperandRequest` instances request to the OperandRegistry.
like 
```
status:
  requestList:
      - name: example
        namespace: default
      - name: example
        namespace: default-1
```

- When `OperandConfig` instances are updated,  `OperandConfig` controller will get the `OperandRequest` instances in its `requestList` and set their status `phase` to `updating`. It is for triggering reconciles of `OperandRequest`.

- When `OperandRegistry` instances are updated,  `OperandRegistry` controller will get the `OperandRequest` instances in its `requestList` and set their status `phase` to `updating`. Moreover, get all the relevant `OperandBindInfo` and update their heir status `phase` to `updating` as well. It is for triggering reconciles of `OperandRequest` and `OperandBindInfo`.

**Comment by DanielXLee** [comment]
@horis233 I think we can add some`labels` when creating the `OperandRequest`, and then update the `OperandRequest` status by query these `labels`

```
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  creationTimestamp: "2020-04-13T08:41:27Z"
  finalizers:
  - finalizer.request.ibm.com
  generation: 2
  labels:
    ibm-common-services.common-service/config: "true"
    ibm-common-services.common-service/registry: "true"
```
