### ISSUE TITLE
Do we need to handle the case of different name for the OperandRegistry and OperandConfig

### ISSUE THREAD

**Issue by DanielXLee** [IBM/operand-deployment-lifecycle-manager#350]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ODLM version:
- Minikube/KIND/OCP version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by DanielXLee** [comment]
Like this case, config name is `test-config`, registry name is `test-registry`
```yaml
apiVersion: operator.ibm.com/v1alpha1
kind: OperandConfig
metadata:
  name: test-config
  namespace: e2e-test-ns-1
spec:
  services:
  - name: etcd
    spec:
      etcdCluster:
        size: 1
  - name: jenkins
    spec:
      jenkins:
        service:
          port: 8081
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRegistry
metadata:
  name: test-registry
  namespace: e2e-test-ns-1
spec:
  operators:
  - channel: singlenamespace-alpha
    name: etcd
    namespace: e2e-test-ns-1
    packageName: etcd
    scope: private
    sourceName: community-operators
    sourceNamespace: openshift-marketplace
  - channel: alpha
    name: jenkins
    namespace: e2e-test-ns-1
    packageName: jenkins-operator
    scope: private
    sourceName: community-operators
    sourceNamespace: openshift-marketplace
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  name: test-request
  namespace: e2e-test-ns-1
spec:
  requests:
  - operands:
    - name: etcd
    - name: jenkins
    registry: test-registry
    registryNamespace: e2e-test-ns-1
```
