### ISSUE TITLE
Absent operator cause other operator depends on deleted

### ISSUE THREAD

**Issue by DanielXLee** [IBM/operand-deployment-lifecycle-manager#464]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
when absent an operator from `common-service` OperandRequest, some operator that depends on by other operators will be deleted.

Example:
1, Create this OperandRequest
```yaml
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  name: common-service
  namespace: ibm-common-services
spec:
  requests:
  - operands:
    - name: ibm-cert-manager-operator
    - name: ibm-mongodb-operator
    - name: ibm-iam-operator
    - name: ibm-healthcheck-operator
    - name: ibm-management-ingress-operator
    - name: ibm-ingress-nginx-operator
    - name: ibm-licensing-operator
    registry: common-service
```

2. Remove `ibm-licensing-operator` from above OperandRequest, the operator `ibm-mongodb-operator` and ` ibm-iam-operator` also will be deleted.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ODLM version:
- Minikube/KIND/OCP version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
