### ISSUE TITLE
manage a single operator with multiple CRs

### ISSUE THREAD

**Issue by horis233** [IBM/operand-deployment-lifecycle-manager#519]
/kind feature

Scenario One:
OperandRequest:

```
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  name: db2-instance1
  namespace: my-service
spec:
  requests:
  - registry: common-service
    namespace: ibm-common-services
    operands:
    - name: ibm-db2-operator
      kind: db2
      spec:
         replicas: 3
```

This CR will install DB2 operator and create a DB2 instance:

name: db2-instance1
namespace: my-service
kind: db2
spec: replicas: 3

Scenario Two:

```
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  name: db2-instance1
  namespace: my-service
spec:
  requests:
  - registry: common-service
    namespace: ibm-common-services
    operands:
    - name: ibm-db2-operator
      kind: db2
      instanceName: db2-instance1
      spec:
         replicas: 3
    - name: ibm-db2-operator
      kind: db2
      instanceName: db2-instance2
      spec:
         replicas: 3
```
If no instanceName is set, then the Cr will use the name of OperandRequest as its name.
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
