### ISSUE TITLE
Creating Operator CRs by OperandRequest

### ISSUE THREAD

**Issue by horis233** [IBM/operand-deployment-lifecycle-manager#636]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

```
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  name: db2-instance1
  namespace: my-service
spec:
  requests:
  - registry: common-service
    namespace: ibm-common-services
    operands:
    - name: ibm-db2-operator
      kind: db2
      instanceName: db2-instance1
      spec:
         replicas: 3
    - name: ibm-db2-operator
      kind: db2
      instanceName: db2-instance2
      spec:
         replicas: 3
```

This CR will install DB2 operator and create two DB2 instances. `db2-instance1` and `db2-instance2` into namespace `my-service`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
