### ISSUE TITLE
Composable Foundation Controller/API

### ISSUE THREAD

**Issue by horis233** [IBM/operand-deployment-lifecycle-manager#643]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

- Composable Foundation Controller/API will be mainly used to manage composable components, like components managed by this operator, enable or disable one component.

- Composable Foundation Controller/API will be used to manage the General parameters for Composable Operators, mainly to manage the lifecycle of a group of operators based on ODLM.

```
apiVersion: operators.ibm.com/v1alpha1
kind: ComposableOperatorRequest
metadata:
  name: applicationManager
spec:
  composableComponents:
  - name: connector-utilities-operator
    enabled: true
  - name: camel-k
    enabled: true
  - name: noi-operator
    enabled: true
  - name: netcool-integrations-operator
    enabled: true
```

ODLM should generate an OperandRequest according to this `ComposableOperatorRequest` CR
The OperandRegistry name and namespace are from the name and namespace of the `ComposableOperatorRequest` CR and `composableComponents` will be converted to the `operands` section of the OperandRequest.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
