### ISSUE TITLE
Allow annotations for operands in OperandConfig

### ISSUE THREAD

**Issue by kaczyns** [IBM/operand-deployment-lifecycle-manager#742]
/kind feature

**Describe the solution you'd like**
I can specify a `spec` for an operand in the OperandConfig, over-riding what is in the `alm-example` for that operand in its operator's CSV.  However I can't over-ride or add annotations in that operand's metadata.  Sometimes an operator looks at the annotations for its operand and performs some extra or different processing which may not be appropriate in my configuration.

I'd like to be able to:
1) change the value for an annotation in the alm-example
2) add an annotation to those already specified in the alm-example

**Anything else you would like to add:**
I am thinking something like this in the OperandConfig would be nice:
```yaml
apiVersion: operator.ibm.com/v1alpha1
kind: OperandConfig
metadata:
  name: my-operandconfig
  namespace: default
spec:
  services:
  - name: my-operator
    spec:
      my-operand:
        some-spec-field: myvalue
    metadata:
      my-operand:
        annotations:
          my-annotation: myannotationvalue
```
