### ISSUE TITLE
configmap "odlm-scope" not found

### ISSUE THREAD

**Issue by arcmop** [IBM/operand-deployment-lifecycle-manager#743]
/kind bug

**What steps did you take and what happened:**
Operator auto update on OCP 4 got fail, the reason is:

`configmap "odlm-scope" not found`

I solved this by creating the empty configmap: 

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: odlm-scope
  namespace: ibm-common-services
data: 
  namespaces: 
```

**What did you expect to happen:**

I reviewed the PR https://github.com/IBM/operand-deployment-lifecycle-manager/pull/542 , I think  it is necsesary add to documentation or to the operator procedure the creation of that empty configmap to avoid issue.

**Anything else you would like to add:**
File afected: config/manager/manager.yaml

**Environment:**
```info
- ODLM version: > 1.5.x 
- Minikube/KIND/OCP version: OCP 4.7.9
- Kubernetes version: (use `kubectl version`): 1.20
- OS (e.g. from `/etc/os-release`): Red Hat Enterprise Linux CoreOS 47.83.202104250838-0 (Ootpa)
```
