### ISSUE TITLE
The customized name of CR is ignored when create OperandRequests

### ISSUE THREAD

**Issue by LiJunBJZhu** [IBM/operand-deployment-lifecycle-manager#747]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Create below OperandRequest by "oc apply" command. The name of Issuer and Certificate is defined by the property "name" under "metadata". However, an Issuer is created as expected, but its name is cert-crs-fab53673af8578, and the name of created certificate is cert-crs-46b4240c9f92f5. Seems the name defined in spec is ignored. 

apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  name: cert-crs
  namespace: zlj-bedrock
spec:
  requests:
  - registry: common-service
    registryNamespace: zlj-bedrock
    operands:
    - name: ibm-cert-manager-operator
      apiVersion: certmanager.k8s.io/v1alpha1
      kind:       Issuer
      metadata:
        **name:      ibm-sample-selfsigned-issuer**
      spec:
        selfSigned: {}
    - name: ibm-cert-manager-operator
      apiVersion: certmanager.k8s.io/v1alpha1
      kind: Certificate
      metadata:
        **name: ibm-sample-serving-cert**
      spec:
        dnsNames:
        - ibm-sample-webhook-service.panamax.svc
        - ibm-sample-webhook-service.panamax.svc.cluster.local
        isCA: false
        issuerRef:
          kind: Issuer
          name: ibm-sample-selfsigned-issuer
        secretName: webhook-server-cert
~                                         

**What did you expect to happen:**
Issuer and certificate should be created with the name defined in spec.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ODLM version: 1.8.0
- Minikube/KIND/OCP version: 4.7
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`): rhel 8.3

**Comment by Daniel-Fan** [comment]
Hi @LiJunBJZhu 

I noticed that you are trying to create custom resources for cert-manager-operator by `OperandRequest`.
May I ask that whether you follow this document to the do that? https://github.com/IBM/operand-deployment-lifecycle-manager/blob/master/docs/design/create-cr-by-operandrequest.md

The CR's name is defined by `instanceName: ibm-sample-selfsigned-issuer`

Here is a complete example, and you can also find it in the above link.
```
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  name: db2-instance1
  namespace: my-service
spec:
  requests:
  - registry: common-service
    registryNamespace: ibm-common-services
    operands:
    - name: ibm-db2-operator
      kind: db2
      apiVersion: operator.ibm.com/v1alpha1
      instanceName: db2-instance1
      spec:
        replicas: 3
    - name: ibm-db2-operator
      kind: db2
      apiVersion: operator.ibm.com/v1alpha1
      instanceName: db2-instance2
      spec:
        replicas: 3
```
