### ISSUE TITLE
ODLM is not deleting the camel-k resources after top level orchestrator operator removed it from the operandrequests

### ISSUE THREAD

**Issue by aadeshpa** [IBM/operand-deployment-lifecycle-manager#786]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

While testing camel-k removal path for WASP 3.3  from orchestrator side, we see that as per our top level operator changes it got removed from the operandrequest , operandregistry and operandconfig, however, we still see the subscription and pod hanging around which was not deleted by ODLM as per expectation.

It is removed from this list in `oc get operandrequests ibm-aiops-application-manager -o yaml`
```
spec:
  requests:
  - operands:
    - name: aiopsedge-operator
    - name: asm-operator
    - name: ir-ai-operator
    - name: ir-core-operator
    - name: ir-lifecycle-operator
    registry: ibm-aiops
    registryNamespace: cp4waiops
....
```
Camel-k pods and subs still seen in the namespace
```
$ oc get subs | grep camel
camel-k                                                                      ibm-camel-k                          ibm-cp-waiops-catalog   0.1-dev
Ashishs-MacBook-Pro-2:3.2 aadeshpa@us.ibm.com$ oc get pods | grep camel
camel-k-operator-ff799b7f6-wtggh                                  1/1     Running     0          16h
Ashishs-MacBook-Pro-2:3.2 aadeshpa@us.ibm.com$ 

```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ODLM version:
- Minikube/KIND/OCP version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
